project_name: openrfsense-node
before:
  hooks:
    - go mod tidy
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

builds:
  - id: node
    main: ./cmd/node
    binary: orfs-node
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      # - windows_amd64
      - linux_arm64
      - linux_arm_7

archives:
  - replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

nfpms:
  - bindir: /usr/bin
    package_name: openrfsense-node
    homepage: https://github.com/openrfsense/node
    maintainer: OpenRFSense Community
    description: |
      OpenRFSense node managment software
    license: AGPLv3
    formats:
      - deb
      - apk
      - rpm
      - archlinux
    version_metadata: git
    contents:
      - src: config.yml
        dst: /etc/openrfsense/config.example.yml
        type: "config|noreplace"
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
