node:
  port: 9090
  location:
    name: Trento
    elevation: 200.0
    latitude: 46.0669256
    longitude: 11.1481102
backend:
  host: "127.0.0.1"
  port: 8081
  username: openrfsense
  password: openrfsense
nats:
  port: 4222